sonar.projectKey=kovendhan5_securedeploy
sonar.projectName=SecureDeploy
sonar.projectVersion=1.0.0
sonar.organization=kovendhan5

sonar.sources=app
sonar.tests=app/tests
sonar.python.version=3.11

# Coverage reports
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverageReportPaths=coverage.xml

# Exclusions
sonar.exclusions=**/__pycache__/**,**/migrations/**,.venv/**,venv/**
sonar.test.exclusions=**/__pycache__/**
